version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "pyproj"
        # pyproj 3.7 and later don't support python 3.9 anymore
        versions: [">= 3.7"]
      - dependency-name: "requests"
        # requests 2.33 and later don't support python 3.9 anymore
        versions: [">= 2.33"]
      - dependency-name: "pytest"
        # pytest 9.0.0 and later don't support python 3.9 anymore
        versions: [">= 9.0"]
